### ISSUE TITLE
Jobs module on course catalog - incorrect typestyle

### ISSUE THREAD

**Issue by andrewpmiller** [gymnasium/tracker#1]
**Summary:** The job module in the right-hand column of the course catalog is not displaying correctly.

**Where:** https://courses.gymna.si/courses

**Note:** Also, the spacing between the text label and the dropdown menu looks incorrect 😉

![image](https://user-images.githubusercontent.com/5747506/70749294-f91bbb00-1cf9-11ea-8259-d7239aaafe82.png)

**Comment by mbifulco** [comment]
Closed via https://github.com/gymnasium/jobs-microservice/pull/36
