### ISSUE TITLE
[Hawthorn] Courseware navigation link color

### ISSUE THREAD

**Issue by jgagne** [gymnasium/tracker#100]
To Do:

- [x] final exam `dashboard` link
- [x] tertiary navigation text for courses ("lessons syllabus forum" on top of the page)

_Originally posted by @mbifulco in https://github.com/gymnasium/tracker/issues/78#issuecomment-716777078_

**Comment by jgagne** [comment]
**Description**

Related to #78, but appears in blue on Hawthorn staging environment.

**Screenshots**

![gym-courseware-navigation-link-color](https://user-images.githubusercontent.com/5142085/98285889-2eb03f00-1f71-11eb-9a80-580b993940f0.png)

**Comment by mbifulco** [comment]
@jgagne what treatment do we want for `lessons syllabus forum`? Black with underline on hover, or something else?

**Comment by jgagne** [comment]
**Style Update**

Consider this treatment…

![gym-courseware-nav-tab-style](https://user-images.githubusercontent.com/5142085/98386028-b5baf100-201d-11eb-9ee3-daadf015a7fd.png)


**CSS**
```
.course-tabs a  {
  color: currentColor !important;
}

.course-tabs a b  {
  color: currentColor !important;
  border-bottom: 1px solid currentColor !important;
}

.course-tabs .active b,
.course-tabs a:hover b,
.course-tabs a:focus b {
  color: currentColor !important;
  border-bottom: 2px solid currentColor !important;
}
```

**Comment by mbifulco** [comment]
<3 @jgagne so helpful - thank you!
