### ISSUE TITLE
[Hawthorn] Account creation / registration not working

### ISSUE THREAD

**Issue by jeremyosborn** [gymnasium/tracker#102]
Not 100% sure if new registrations are not supposed to work for courses.gymnasium.dev, but I was unable to create an account after filling in all the fields. The "Create Your Account" button was inactive.

https://courses.gymnasium.dev/register

**Screenshots**
<img width="574" alt="register" src="https://user-images.githubusercontent.com/6589523/98292976-923f6a00-1f7b-11eb-8fbf-555acc10cc69.png">

**Comment by mbifulco** [comment]
This should be working once again! It was a configuration issue.
