### ISSUE TITLE
[Hawthorn] Account Settings page is incorrectly styled

### ISSUE THREAD

**Issue by jeremyosborn** [gymnasium/tracker#106]
The "Account Settings" and "Linked Accounts" navigation are unstyled and also the order of the content is slightly different than the existing production page. (Note how the "Basic Account Information" and the paragraph following it are swapped.)

https://courses.gymnasium.dev/account/settings

courses.gymnasium.dev layout
<img width="1181" alt="Screen Shot 2020-11-05 at 4 20 06 PM" src="https://user-images.githubusercontent.com/6589523/98297982-45f82800-1f83-11eb-8c4d-0878d40278ad.png">

current thegymnasium.com  layout
<img width="1194" alt="Screen Shot 2020-11-05 at 4 20 15 PM" src="https://user-images.githubusercontent.com/6589523/98297918-2b25b380-1f83-11eb-9988-f046e99df5eb.png">

**Comment by jgagne** [comment]
Update navigation style for consistency and other readability improvements; see also #125
