### ISSUE TITLE
[Hawthorn] Activation link after registering appears to be broken

### ISSUE THREAD

**Issue by jeremyosborn** [gymnasium/tracker#108]
Not sure if it's the throwaway webmail service I was using, but the activate hyperlink in the email that a new registrant receives appears to be broken.  Additionally, the link pointing to our web form is blank and the help@thegymnasium.com email is not active. Again, could be my shitty webmail, haven't tried it elsewhere.

**URL where bug occurs**
https://courses.gymnasium.dev/register?next=%2F

**Screenshots**
<img width="1058" alt="reg-link" src="https://user-images.githubusercontent.com/6589523/98408068-9aaca900-203e-11eb-98ee-3141e3b183f0.png">

**Comment by mbifulco** [comment]
I'm going to have Amir take a look at the settings here

**Comment by mbifulco** [comment]
This is all set!

**Comment by valpierre** [comment]
Just a comment to confirm I checked and confirm that registration/enrollment/password emails all contain the proper links.
