### ISSUE TITLE
Add OG related content for hub pages

### ISSUE THREAD

**Issue by jgagne** [gymnasium/tracker#11]
Todos:

**UX**
- [x] OG art
- [x] OG meta

**Prototyping**
- [x] OG art
- [x] OG meta

**Web Dev**
- [x] OG art
- [x] OG meta

**Career Skills**
- [x] OG art
- [x] OG meta

Notes:

Update to use larger summary card size

**Comment by mbifulco** [comment]
@jgagne a heads up - I moved this issue to the tracker repo 👍
