### ISSUE TITLE
[Hawthorn] Bookmarking is not working

### ISSUE THREAD

**Issue by andrewpmiller** [gymnasium/tracker#114]
1. Navigate to a course
2. Navigate to a lesson
3. Click "Bookmark" button on right side
4. Error message appears (see screenshot detail) and bookmark is not created
5. Click "Bookmarks" button on left side
6. There is no result — expected behavior is a display of all bookmarks for that course (see screenshot)

## Screenshots

Error message when attempting to add a bookmark

![image](https://user-images.githubusercontent.com/5747506/98603582-4c064580-22b0-11eb-8089-7261177920a0.png)

---

Expected behavior (on courses.gymna.si — staging)

![image](https://user-images.githubusercontent.com/5747506/98603722-8ff94a80-22b0-11eb-8071-ebc836ae45c6.png)

**Comment by mbifulco** [comment]
Mike to hide bookmarks, because they're 🤮  now
