### ISSUE TITLE
Error when trying to login after I've authorized LinkedIn

### ISSUE THREAD

**Issue by valpierre** [gymnasium/tracker#115]
@mbifulco After having entered the email and password for my LinkedIn account, I got an error and wasn't able to login into the LMS. 

Steps to reproduce: 
- On the login page, click on the LinkedIn button
- It opens a linkedin page, where I enter the email and password for my LinkedIn account.
- Then it opens the LMS page with a URL that starts with https://courses.gymnasium.dev/auth/complete/linkedin-oauth2/?code=....  and displays the error "THERE HAS BEEN A 500 ERROR ON THE GYMNASIUM STAGING SERVERS. Please wait a few seconds and then reload the page. If the problem persists, please email us at technical+aquent@appsembler.com."
- Note: I checked my LinkedIn settings and I see it added Gymnasium as a permitted service.

<img width="827" alt="Screen Shot 2020-11-09 at 4 21 04 PM" src="https://user-images.githubusercontent.com/30666924/98612445-0bef9480-22a9-11eb-80be-11b113d1376e.png">
<img width="1185" alt="Screen Shot 2020-11-09 at 4 17 47 PM" src="https://user-images.githubusercontent.com/30666924/98612449-0e51ee80-22a9-11eb-899b-df29ff25fc0c.png">

**Comment by amirtds** [comment]
@valpierre @mbifulco The LinkedIn issue is solved. I could log in successfully

**Comment by valpierre** [comment]
@amirtds after entering the email and pwd for LN, I saw the form saying, “You’ve successfully signed into LinkedIn. We just need a little more information before you start learning with Gymnasium STAGING.” After I fill it in, it seems it won't take my email address valpierresf@gmail.com, is it maybe because that account already got created? how could I test this again?

**Comment by mbifulco** [comment]
@valpierre that is an unfortunate catch with testing LinkedIn authentication - you'd need to create a new account to test with.  Luckily I've got a few accounts on hand, and I just tested.  It looks like it's working! I'm going to close this one out.

![image](https://user-images.githubusercontent.com/1844496/98712630-888b7d00-2354-11eb-94f3-fdfc3d74b5af.png)

**Comment by valpierre** [comment]
Yep, that's what I thought. Great that you could test with a new account, thanks!
