### ISSUE TITLE
[Hawthorn] On the final exam page for Full Courses, "certificates" are referred to as "badges".

### ISSUE THREAD

**Issue by jeremyosborn** [gymnasium/tracker#117]
**Description**

On both Hawthorn as well as our current site, the wording on the exam page, as well as the button, defaults to the word "badge", on full courses.
For example, a successful pass of "Modern Web Design" refers to a badge not a certificate (as seen here). 

**URL where bug occurs**
https://courses.gymnasium.dev/courses/GYM/107/0/courseware/30051071400e47aeb15d5eeb943d7c14/e19904ca61614c0493989065b3627367/

**Screenshots**
<img width="1178" alt="production-site" src="https://user-images.githubusercontent.com/6589523/98707395-fda78400-234d-11eb-9860-9da0e3530b50.png">

**Comment by mbifulco** [comment]
This comes from [gymcms](https://github.com/gymnasium/gymcms/blob/staging/final-exam-modal-top.html#L8) - there's already a solution in place for this for the try again message... we can do the same for the congratulatory one.

**Comment by mbifulco** [comment]
![image](https://user-images.githubusercontent.com/1844496/98737309-06ab4c00-2374-11eb-8b7b-ea557c1736b7.png)

Fixed!
