### ISSUE TITLE
Registration form validation issue

### ISSUE THREAD

**Issue by valpierre** [gymnasium/tracker#119]
STR:
- Go to https://courses.gymna.si/register
- Fill in the form, but enter a password that doesn't match the criteria and also omit checking the Terms of Services checkbox
- You see the red styling showing you where things are incorrect, and the Create Your Account button is "grayed out"
- you fix them by entering password that matches the criteria, and check the ToS checkbox
- Still the form is stuck with those red styling on the password and ToS fields and the Create Your Account button remains "grayed out", so you can't proceed. 

Screenshot taken on the last step above:
<img width="983" alt="Screen Shot 2020-11-11 at 10 10 16 AM" src="https://user-images.githubusercontent.com/30666924/98848674-eed0d800-2406-11eb-8f52-f324e152aef0.png">

**Comment by valpierre** [comment]
@mbifulco sorry I missed that one yesterday in my testing on staging. From what I could see, Form validation works fine until you click the Create Your Account, once you've clicked it once _and_ you had something incorrect in the form, the styling remain stuck and you can't create your account.

**Comment by mbifulco** [comment]
Rats, okay - I'm looking into it!

**Comment by valpierre** [comment]
Great, I just tried and confirm the issue is fixed on staging.
