### ISSUE TITLE
[Hawthorn] Educate "You're close!" apostrophes

### ISSUE THREAD

**Issue by jgagne** [gymnasium/tracker#121]
**Description**

All apostrophes (in the heading and body text) that appear in the final exam of the "You're close!" message need to be educated/curly rather straight. The only educated apostrophe is circled in red in the screenshot.

**URL where bug occurs**

Failed final exam attempt within each course.

**Screenshots**

![gym-final-exam-close-mesage-text-punctuation](https://user-images.githubusercontent.com/5142085/98856207-3c5f3c00-242b-11eb-87df-44d1f8cd5bd1.png)

**Comment by mbifulco** [comment]
@jgagne I can't believe you circled the apostrophe in that screenshot, and not the `55.00000000000001` 😂

**Comment by jgagne** [comment]
@mbifulco I thought that was already a known bug — it’s all about priorities 😂

**Comment by andrewpmiller** [comment]
It's all in here: https://github.com/gymnasium/gymcms/blob/staging/final-exam-modal-top.html#L31-L45
