### ISSUE TITLE
[Hawthorn] In Forum, on mouse-over “All Topics”, the text disappears

### ISSUE THREAD

**Issue by valpierre** [gymnasium/tracker#124]
**Description**
Go to a Forum, for example https://thegymnasium.com/courses/GYM/100/0/discussion/forum/
Mouse-over “All Topics”, you'll see the text All Topics disappears.

**URL where bug occurs**
https://thegymnasium.com/courses/GYM/100/0/discussion/forum/

**Screenshots**
<img width="500" alt="Screen Shot 2020-11-11 at 5 33 26 PM" src="https://user-images.githubusercontent.com/30666924/98884473-f911c700-2444-11eb-8053-023d7fd40eaf.png">

**Comment by andrewpmiller** [comment]
@jgagne: 

- Consider hiding the "All Topics" nav component completely?
- Consider hiding the Filter topics field?
- Consider hiding the search field and button (unless this functionality is restored)?
