### ISSUE TITLE
[Hawthorn] Gymnasium logo overlaps Sign Up CTA

### ISSUE THREAD

**Issue by jgagne** [gymnasium/tracker#126]
**Description**

Gymnasium logo slightly overlaps the top left Sign Up CTA, and the CTA slightly overlaps the section it is in.

**URL where bug occurs**

- https://courses.gymna.si
- https://thegymnasium.com

**Screenshots**

![gym-logo-overlap-detail](https://user-images.githubusercontent.com/5142085/98995691-b2cd6e00-24ff-11eb-946d-76214c78f057.png)

![gym-logo-overlap](https://user-images.githubusercontent.com/5142085/98995202-fe334c80-24fe-11eb-9753-2ab993787b59.png)

**Comment by rediris** [comment]
@jgagne we can either make the button smaller or make the navbar taller - I'm leaning towards the former. Let me know if you have a preference, but I'll do a quick PR making the button smaller.

**Comment by jgagne** [comment]
@rediris consider expanding the height to accommodate the full height of the button and icons for balanced vertical spacing.

**Full-Width**

![gym-navbar-height](https://user-images.githubusercontent.com/5142085/106070803-22043880-60d3-11eb-8982-575e477868cd.png)

**Detail**

![gym-navbar-height-detail](https://user-images.githubusercontent.com/5142085/106071275-0e0d0680-60d4-11eb-9271-632961d512cb.png)
