### ISSUE TITLE
[Hawthorn] Reset password form needs styling

### ISSUE THREAD

**Issue by jgagne** [gymnasium/tracker#127]
**Description**

Reset password form needs a style update.

**URL where bug occurs**

- https://courses.gymna.si/password_reset_confirm/
- https://courses.gymna.si/password_reset_confirm/x6h-5lj-46c4cb5a1887f0c8bc37/?utm_content=76f235d4-63bf-4b24-9436-0f96fe1425ce&utm_medium=email&utm_source=student&utm_campaign=passwordreset

**Screenshots**

![gym-reset-passord-form](https://user-images.githubusercontent.com/5142085/99009846-bd473200-2516-11eb-8b00-6147a1cc949f.png)

**Comment by jgagne** [comment]
@mbifulco — Without altering the HTML, these CSS rules will resolve the display of this form. 

Are there any other forms we need to wrangle?

**Note:** The first three rulesets are updates to rules that have already been added to the template.

```

.login-register {
  max-width: none;
  min-width: none;
}

.login-register .form-type {
  min-width: none;
}

#login,
#register,
#passwordreset-form {
  padding: 0 1.8em 2.2em;
}

#passwordreset-form {
  padding-top: 1.8em;
}

#passwordreset-form h2.section-title {
  font: 900 2.2em/1.15 brandon-grotesque, "Helvetica Neue", Helvetica, sans-serif;
  color: #333;
  letter-spacing: 0.01em;
  word-spacing: 0.04em;
  margin-top: 0;
}

#passwordreset-form h2.lines {
  text-align: left;
}

#passwordreset-form h2.lines::after {
  display: none;
}

#passwordreset-form h2.lines .text {
  position: static;
  top: 0;
  z-index: auto;
  font-size: inherit;
  background: none;
  padding: 0;
}

#passwordreset-form .paragon__invalid-feedback {
  font-size: unset;
}

#passwordreset-form .action-primary {
  margin-top: 0;
}

#passwordreset-form .action-primary {
  width: 100%;
  font: bold 1.5em/1 brandon-grotesque, "Helvetica Neue", Helvetica, sans-serif;
  background-color: #f8971d;
  padding: 1em;
  border-radius: .125em;
}

#passwordreset-form .action-primary:hover,
#passwordreset-form .action-primary:focus,
#passwordreset-form .action-primary:active {
  background-color: #a6a6a6;
}
```

**Before:**

![gym-reset-password-form-before](https://user-images.githubusercontent.com/5142085/99091978-946a7f80-259e-11eb-8cfa-e5e29ae31b91.png)
![gym-reset-password-form-tip-before](https://user-images.githubusercontent.com/5142085/99091986-96ccd980-259e-11eb-9208-417aef0636f8.png)

**After:**

![gym-reset-password-form-after](https://user-images.githubusercontent.com/5142085/99092003-9d5b5100-259e-11eb-9b75-1fb47d9682eb.png)
![gym-reset-password-form-tip-after](https://user-images.githubusercontent.com/5142085/99092014-a0eed800-259e-11eb-8532-8c3e6c722226.png)

**Comment by mbifulco** [comment]
Oh oof - I don't know how I missed that it was unstyled.  The other forms look good still - register / login are both good.

**Comment by mbifulco** [comment]
Does it make sense to put this into the theme?

**Comment by jgagne** [comment]
I'm cool with adding these styles to the CMS, since it's mostly a crowbar right now without updating the HTML in this template.

**Comment by jgagne** [comment]
I'll serve up a PR, if that works?
