### ISSUE TITLE
Account Settings - account deletion email address is incorrect

### ISSUE THREAD

**Issue by andrewpmiller** [gymnasium/tracker#131]
Account deletion requests should go to help@thegymnasium.com

![image](https://user-images.githubusercontent.com/5747506/99307219-2e8f2980-2824-11eb-8d24-dcf7d29e071f.png)

**Comment by andrewpmiller** [comment]
## My suggestion:
Serve the content that appears below the section heading (i.e. below DELETE MY ACCOUNT) from the gymcms.

![image](https://user-images.githubusercontent.com/5747506/101681218-d49f0f80-3a2f-11eb-8a16-7b408553f077.png)

In anticipation of this update, these content includes will be in place shortly.
- For the staging site: http://staging.thegymcms.com/static/account-deletion/
- For the production site: http://thegymcms.com/static/account-deletion/

**Comment by amirtds** [comment]
@andrewpmiller  This got more complicated than what I thought. The account deletion piece is a React script https://github.com/appsembler/edx-platform/blob/appsembler/hawthorn/master/lms/static/js/student_account/components/StudentAccountDeletion.jsx#L44, and we can't change it from the theme. I tried different ways:
1. Overriding template file in our theme
2. Using dirty way by overriding it with jQuery script
but none of the above worked, the only way is we need to create a new branch for Gymnasium and change the text there which is not an ideal way for us. I keep digging to see if I can find a better solution for this than creating a new branch.
