### ISSUE TITLE
Open edX logo in footer is squashed

### ISSUE THREAD

**Issue by andrewpmiller** [gymnasium/tracker#137]
The aspect ratio seems to be incorrect — possibly related to recent breakpoint updates for the footer?

![image](https://user-images.githubusercontent.com/5747506/107092039-c91e5980-67d0-11eb-9a73-c75b908ae388.png)

The correct aspect ratio:
![image](https://user-images.githubusercontent.com/5747506/107092298-55c91780-67d1-11eb-93da-b679ac80eab2.png)

**Comment by rediris** [comment]
Could probably remedy by removing width & height attributes and using a max-height inline style attribute of 70px instead?
