### ISSUE TITLE
Update Setting Up Pattern Lab instructions

### ISSUE THREAD

**Issue by jgagne** [gymnasium/tracker#138]
**Description**

Update GYM-014 Working With Atomic Design and Pattern Lab's Chapter 4, Setting Up Pattern Lab install instructions.

**URL**

Chapter 4: Setting Up Pattern Lab
https://courses.gymna.si/courses/course-v1:GYM+014+0/courseware/

**Notes**

- Update NPM install instructions
- Remove Gulp install instructions

**Comment by jgagne** [comment]
`work-in-progress`

## macOS

1. Install Command Line Tools

Apple provides a collection of core libraries and utilities for developers, but they aren’t automatically installed with the system software. In case you need it, the official Apple documentation can be found at [developer.apple.com](https://developer.apple.com). (Please note that you will need an Apple ID to access this site, however, you do *not* need an Apple ID to complete the following steps.)

- To install the Command Line Tools for the first time, or to update or fix a prior installation, use the following command: (Note the double hyphen.)
  - `xcode-select --install`
- If you see errors indicating that you don’t have permission to complete the install, you can install them as a “superuser” with the following variation of the previous command (you’ll be prompted to enter your administrator password):
  - `sudo xcode-select --install`
- To verify the installation, the following command will display the version of the Command Line Tools that you’ve installed:
  - `xcode-select --version`

2. Install Homebrew

If you haven’t used [Homebrew](https://brew.sh) before, it is technically a “package manager”, but you can think of it as an app store for command line tools. It simplifies finding, installing, and updating (literally) thousands of useful and powerful applications and utilities.

- To install Homebrew for the first time:
 - `/bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"`
- To verify that you actually installed Homebrew:
  - `brew --version`
- To update Homebrew, type:
  - `brew update`
- To update any of the tools that you've installed with Homebrew:
  - `brew upgrade`
- To check Homebrew for issues:
  - `brew doctor`
- This is a list of commonly encountered problems, known issues, and their solutions:
  - [Common Issues](https://docs.brew.sh/Common-Issues)

3. Intall Pattern Lab, Node Edition

- Choose where to install Pattern Lab:
  - For example, use the change directory command to move to your Desktop (or anywhere else):
    - `cd Desktop`
  - Then, make a new directory/folder on your Desktop:
    - `mkdir patternlab`
- Now, change directory to `patternlab`:
  - `cd patternlab`
- Install Node.js:
  - `brew install npm`
- Install Pattern Lab
  - `npm create pattern-lab`
- Prompt: **Please specify a directory for your Pattern Lab project. (./)**
  - Press **return** (to select `./` which by default installs Pattern Lab to your `patternlab` directory you made earlier).
- Prompt: **What templating language do you want to use with Pattern Lab? (Use arrow keys)**
  - Choose `Handlebars`, the default choice.
  - Press **return**.
- Prompt: **What initial patterns do you want included in your project? (Use arrow keys)**
  - Choose `Handlebars demo patterns (full demo website and patterns) `
  - Press **return**.
- Prompt: **Are you happy with your choices? (Hit enter for YES)? (Y/n)**
  - Press **return** (for YES).
- Serve Pattern Lab
  - `npm run pl:serve`
- View Pattern Lab in a browser via the URL:
  - `http://127.0.0.1:3000`
  - **Note:** A new tab/window with this URL may automatically open in your default browser

**Comment by andrewpmiller** [comment]
@jgagne — this is pretty solid. I have a couple of thoughts:

1. I wonder if it makes sense to be more specific about how and where these commands are used. We just say "use the command" but I think we should clarify in the beginning that the command line instructions are entered at the prompt in the Terminal application (which is found in /Applications/Utilities).
2. Installing Pattern Lab from NPM will display a lot of output as it runs — including a likely slew of warnings. Do we tell students to ignore those?

**Comment by jgagne** [comment]
@andrewpmiller —  Agreed, 1. clarifying use and location of the Terminal app is a smart decision, and 2. a comment about process, time, and possible warmings during the installation of Pattern Lab from NPM would be helpful. I'll update and keep you posted.

**Comment by jgagne** [comment]
`revision-1`

## macOS

Setting up Pattern Lab locally on your computer involves installing content via the command line using the utility application Terminal, located in the Applications’ Utilities folder (`/Applications/Utilities/Terminal`).

To set up Pattern Lab, you’ll need to install Command Line Tools and Homebrew first, then Pattern Lab (Node Edition).

- To start, open Terminal and follow steps 1, 2, and 3 in the order they appear.

1. Install Command Line Tools

Apple provides a collection of core libraries and utilities for developers, but they aren’t automatically installed with the system software. In case you need it, the official Apple documentation can be found at [developer.apple.com](https://developer.apple.com). (Please note that you will need an Apple ID to access this site, however, you do *not* need an Apple ID to complete the following steps.)

- To install the Command Line Tools for the first time, or to update or fix a prior installation, use the following command: (Note the double hyphen.)
  - `xcode-select --install`
- If you see errors indicating that you don’t have permission to complete the install, you can install them as a “superuser” with the following variation of the previous command (you’ll be prompted to enter your administrator password):
  - `sudo xcode-select --install`
- To verify the installation, the following command will display the version of the Command Line Tools that you’ve installed:
  - `xcode-select --version`

2. Install Homebrew

If you haven’t used [Homebrew](https://brew.sh) before, it is technically a “package manager”, but you can think of it as an app store for command line tools. It simplifies finding, installing, and updating (literally) thousands of useful and powerful applications and utilities.

- To install Homebrew for the first time:
  - `/bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"`
- To verify that you actually installed Homebrew:
  - `brew --version`
- To update Homebrew:
  - `brew update`
- To update any of the tools that you've installed with Homebrew:
  - `brew upgrade`
- To check Homebrew for issues:
  - `brew doctor`
- This is a list of commonly encountered problems, known issues, and their solutions:
  - [Common Issues](https://docs.brew.sh/Common-Issues)

3. Intall Pattern Lab (Node Edition)

- Choose where to install Pattern Lab:
  - For example, use the change directory command to move to your Desktop (or anywhere else):
    - `cd Desktop`
  - Then, make a new directory/folder on your Desktop:
    - `mkdir patternlab`
- Now, change directory to `patternlab`:
  - `cd patternlab`
- Install Node.js:
  - `brew install npm`
- Install Pattern Lab:
  - `npm create pattern-lab`
  - **Note:** During the `create` process, Terminal will display a lot of output (information) as it runs tasks, including potential warnings (ignore unless an error occurs) and various prompts that require your interaction to complete setting up Pattern Lab.
- Prompt: **Please specify a directory for your Pattern Lab project. (./)**
  - Press <kbd>return</kbd> (to select `./` which by default installs Pattern Lab to the `patternlab` directory you made earlier).
- Prompt: **What templating language do you want to use with Pattern Lab? (Use arrow keys)**
  - Choose `Handlebars`, the default choice.
  - Press <kbd>return</kbd>.
- Prompt: **What initial patterns do you want included in your project? (Use arrow keys)**
  - Choose `Handlebars demo patterns (full demo website and patterns)`
  - Press <kbd>return</kbd>.
- Prompt: **Are you happy with your choices? (Hit enter for YES)? (Y/n)**
  - Press <kbd>return</kbd> (for YES).
- Serve Pattern Lab:
  - `npm run pl:serve`
- View Pattern Lab in a browser via the URL:
  - `http://127.0.0.1:3000`
  - **Note:** A new tab/window with this URL may automatically open in your default browser.

**Comment by andrewpmiller** [comment]
### How to use Pattern Lab with GitPod (aka Pattern Lab the Easy Way)

1. Click this ![Gitpod ready-to-code](https://camo.githubusercontent.com/daadb4894128d1e19b72d80236f5959f1f2b47f9fe081373f3246131f0189f6c/68747470733a2f2f696d672e736869656c64732e696f2f62616467652f476974706f642d72656164792d2d746f2d2d636f64652d626c75653f6c6f676f3d676974706f64) button (it also appears on the README for the Pattern Lab repo)
2. You will be redirected to the GitPod site where you'll be prompted to log in using your GitHub account
3. Sit back and watch while GitPod creates a workspace for your project and installs Pattern Lab
   - Note: the first time GitPod creates the workspace it may take a few minutes
   - You can safely ignore any of the warnings about some of the npm packages as they're getting installed
   - You're ready to use Pattern Lab as soon as the terminal window in GitPod shows this prompt:
     `gitpod /workspace/patternlab $ `
4. To start Pattern Lab, locate the tool palette on the lower left-hand side of your workspace window that is titled "NPM SCRIPTS" and click the triangular icon that appears when you hover your cursor over the "pl:serve" item. Pattern Lab's interface will appear in a new browser tab.
   - Alternatively, you can type the command `npm run pl:serve`  into the terminal window in your workspace and press return to run Pattern Lab

#### What is GitPod?

GitPod is a cloud-based service that will let you build and run software directly from within the GitHub repository where that code is maintained — without needing to install anything on your computer! GitPod creates a virtual workspace that looks and works almost exactly like VS Code, only it's all in your web browser. You can edit your project files and commit changes back to your repo. You can pause your workspace and restart it when you're ready to do more work on your project and you can share your workspace to collaborate with teammates in real time. GitPod is free for up to 100 hours of use each month.



#### How do I save my work?

TK

#### How do I stop my workspace?

TK

**Comment by jgagne** [comment]
`version-2`

**Notes:** The instructions below differ from the instructions presented in the <cite>Setting Up Pattern Lab</cite> video chapter content.

# Setting Up Pattern Lab on macOS

If this is the first time you’re installing command line tools like [Homebrew](https://brew.sh) and [NPM](https://www.npmjs.com), here’s a reference that can help you avoid some of the frustrations. We recommend that you follow these steps in sequence, as we’re basically installing things that allow us to… install things. There are sections of this guide that are depicted like so:

```
code
```

Below are the commands you need to type (or copy) at the command line of your terminal application. By default, your Mac will have an application called Terminal (you’ll find it in the Utilities folder that’s inside the Applications folder [`/Applications/Utilities/Terminal`]).

- As a warm-up, open Terminal, and type or copied the following command, then press the <kbd>return</kbd> key on your keyboard:

```
xcode-select --version
```

Terminal will return the follow `xcode-select version xxxx` output, for example:

```
xcode-select version 2354
```

## Get Started

To set up Pattern Lab, you’ll need to install Command Line Tools and Homebrew first, then Pattern Lab (Node Edition).

- To start, open Terminal and follow steps 1, 2, and 3 in the order they appear.

1. **Install Command Line Tools**

Apple provides a collection of core libraries and utilities for developers, but they aren’t automatically installed with the system software. In case you need it, the official Apple documentation can be found at [developer.apple.com](https://developer.apple.com). (Please note that you will need an Apple ID to access this site, however, you do *not* need an Apple ID to complete the following steps.)

- To install the Command Line Tools for the first time, or to update or fix a prior installation, use the following command: (Note the double hyphen.)
  - `xcode-select --install`
- If you see errors indicating that you don’t have permission to complete the install, you can install them as a “superuser” with the following variation of the previous command (you’ll be prompted to enter your administrator password):
  - `sudo xcode-select --install`
- To verify the installation, the following command will display the version of the Command Line Tools that you’ve installed:
  - `xcode-select --version`

2. **Install Homebrew**

If you haven’t used [Homebrew](https://brew.sh) before, it is technically a “package manager”, but you can think of it as an app store for command line tools. It simplifies finding, installing, and updating (literally) thousands of useful and powerful applications and utilities.

- To install Homebrew for the first time:
  - `/bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"`
- To verify that you actually installed Homebrew:
  - `brew --version`
- To update Homebrew:
  - `brew update`
- To update any of the tools that you've installed with Homebrew:
  - `brew upgrade`
- To check Homebrew for issues:
  - `brew doctor`
- This is a list of commonly encountered problems, known issues, and their solutions:
  - [Common Issues](https://docs.brew.sh/Common-Issues)

3. **Install Pattern Lab (Node Edition)**

- Choose where to install Pattern Lab:
  - For example, use the change directory command to move to your Desktop (or anywhere else):
    - `cd Desktop`
  - Then, make a new directory/folder on your Desktop:
    - `mkdir patternlab`
- Now, change directory to `patternlab`:
  - `cd patternlab`
- Install Node.js:
  - `brew install npm`
- Install Pattern Lab:
  - `npm create pattern-lab`
  - **Note:** During the `create` process, Terminal will display a lot of output (information) as it runs tasks, including potential warnings (ignore unless an error occurs) and various prompts that require your interaction to complete setting up Pattern Lab.
- Prompt: **Please specify a directory for your Pattern Lab project. (./)**
  - Press <kbd>return</kbd> (to select `./` which by default installs Pattern Lab to the `patternlab` directory you made earlier).
- Prompt: **What templating language do you want to use with Pattern Lab? (Use arrow keys)**
  - Choose `Handlebars`, the default choice.
  - Press <kbd>return</kbd>.
- Prompt: **What initial patterns do you want included in your project? (Use arrow keys)**
  - Choose `Handlebars demo patterns (full demo website and patterns)`
  - Press <kbd>return</kbd>.
- Prompt: **Are you happy with your choices? (Hit enter for YES)? (Y/n)**
  - Press <kbd>return</kbd> (for YES).
- Serve Pattern Lab:
  - `npm run pl:serve`
- View Pattern Lab in a browser via the URL:
  - `http://127.0.0.1:3000`
  - **Note:** A new tab/window with this URL may automatically open in your default browser.

**Comment by andrewpmiller** [comment]
Gitpod Pattern Lab instructions (draft) added to the Readme here: https://github.com/gymnasium/patternlab
