### ISSUE TITLE
Live Coding hero display issue w/ Chromium - Linux

### ISSUE THREAD

**Issue by andrewpmiller** [gymnasium/tracker#14]
**Chromium**
`Version 78.0.3904.108 (Official Build) Built on Raspbian, running on Raspbian 10 (32-bit)`

The embedded Twitch viewer does not fill the full width of the hero.

![screenshot](https://user-images.githubusercontent.com/5747506/72449925-761dd280-3787-11ea-8248-7b45b00be19b.png)

**Comment by andrewpmiller** [comment]
![2020-01-21-140044_1360x768_scrot](https://user-images.githubusercontent.com/5747506/72834925-c8fbfc00-3c57-11ea-9424-4c0eebdb5805.png)

**Comment by andrewpmiller** [comment]
### Fixed!

![2020-03-10-145236_1360x768_scrot](https://user-images.githubusercontent.com/5747506/79142146-0967a380-7d89-11ea-9080-e52867247f4d.png)

**Comment by andrewpmiller** [comment]
@jgagne — you happy to close this one?

**Comment by jgagne** [comment]
@andrewpmiller — Looks great!
