### ISSUE TITLE
Dashboard fails loading paragon font assets

### ISSUE THREAD

**Issue by rediris** [gymnasium/tracker#154]
The Gymnasium theme design doesn't use them, so this must be something built into edX. The quick and dirty solution would be to prevent them loading entirely.

<img width="411" alt="Screen Shot 2021-04-07 at 9 29 10 AM" src="https://user-images.githubusercontent.com/1010395/113874388-c1a10f80-9783-11eb-935e-0bf77b41f4f1.png">

**Comment by andrewpmiller** [comment]
@rediris possibly related to the admin screens (for staff and students)?
https://github.com/gymnasium/openedx-theme/search?q=paragon
