### ISSUE TITLE
Last item in course navigation (Final exam) appears vertically truncated

### ISSUE THREAD

**Issue by andrewpmiller** [gymnasium/tracker#182]
When you click on the Final Exam section on the course navigation, and the Final Exam item expands, it appears to be cut off on the bottom. It might not be... but it seems to be. Maybe just an illusion...?

![image](https://user-images.githubusercontent.com/5747506/129416319-633d3c9f-7fc8-45fb-89f9-d0c9a45af286.png)

**Comment by rediris** [comment]
@andrewpmiller I think this is an optical illusion. I scaled up the orange text to match the font size of the white text and you can see the comparison for yourself here:

https://user-images.githubusercontent.com/1010395/133285775-a53427d0-5279-47be-8971-5c83a218a5da.mp4

**Comment by andrewpmiller** [comment]
![](https://media.giphy.com/media/H1RZU2TyEalt5MJ448/giphy-downsized-large.gif)
@rediris we can close this. Thanks for the analysis!
