### ISSUE TITLE
Update Gym description(s)

### ISSUE THREAD

**Issue by andrewpmiller** [gymnasium/tracker#187]
Update description copy in: 

- Featured Courses module (`_includes/home/featured-courses.html`)
- Catalog prototype (`/dev/prototypes/courses/comp-1.html`)

**Old copy:** Design a career you love with free online courses on web design and development, user experience, accessibility, career skills, prototyping, and content creation.

**New copy:** Design a career you love with free online courses on web design and development, accessibility, UX, prototyping, content creation, and career skills.

- Meta description
  - `/home/meta.md`
  - `/courses/meta.md`

**META copy:** Design a career you love with free online courses on web design and development, accessibility, UX, prototyping, content creation, and career skills.

**Comment by rediris** [comment]
@andrewpmiller presumably this one is already done? I'm thinking we can close this.
