### ISSUE TITLE
Consider a server-side redirect for bad links to GYM-103

### ISSUE THREAD

**Issue by andrewpmiller** [gymnasium/tracker#188]
Numerous blogs have an incorrect url for GYM-103.

`https://www.thegymnasium.com/courses/GYM/103/0/abou` should redirect to `https://www.thegymnasium.com/courses/GYM/103/0/about`

**Comment by rediris** [comment]
We will likely need Appsembler's help with this. I'll reach out to Amir.

**Comment by rediris** [comment]
Trello card created: https://trello.com/c/DEQo9nU5/87-we-have-a-redirect-request-there-are-some-blogs-that-are-linking-to-a-bad-url-and-we-were-hoping-to-create-a-redirect-to-the-pro

**Comment by rediris** [comment]
Resolved by the Appsemblers...
