### ISSUE TITLE
Use hi-resolution favicon

### ISSUE THREAD

**Issue by rediris** [gymnasium/tracker#196]
Instead of this:
![image](https://user-images.githubusercontent.com/1010395/139281830-a0193340-80c1-4407-ade7-1040aaefa159.png)

Use SVG if possible.

**Comment by jgagne** [comment]
@redis `update`

Before:

`<link rel="icon" type="image/x-icon" href="/static/gymnasium/images/favicon.f729730b6e79.ico">`

Note: Check meta for other references.

After:

```
<link rel="alternate icon" href="https://thegymcms.com/img/gym-favicon/favicon.ico" sizes="any">
<link rel="icon" href="https://thegymcms.com/img/gym-favicon/favicon.svg">
```


Updated versions:

(Soon to be on staging/production.)

- https://github.com/gymnasium/gymcms/blob/feature/brand-alignment-phase-1/img/gym-favicon/favicon.ico
- https://github.com/gymnasium/gymcms/blob/feature/brand-alignment-phase-1/img/gym-favicon/favicon.svg

**Comment by rediris** [comment]
@jgagne I think a good solution for a coordinated theme/gymcms release would be to move that markup out of theme into the gymcms meta block.
