### ISSUE TITLE
LinkedIn authentication content is not displaying correctly

### ISSUE THREAD

**Issue by andrewpmiller** [gymnasium/tracker#2]
**Summary:** When authenticating with LinkedIn, text content on one of the critical screens is not displaying correctly — it is not readable.

**Where:** Staging and Production registration/login screens

![image](https://user-images.githubusercontent.com/5747506/70749755-fe2d3a00-1cfa-11ea-93f2-e39678ee1ed6.png)

**Comment by mbifulco** [comment]
Near as I can tell, this was indeed fixed 👍 

![image](https://user-images.githubusercontent.com/1844496/73192552-2fb96380-40f7-11ea-9453-37c1ff377ed6.png)

![image](https://user-images.githubusercontent.com/1844496/73192574-37790800-40f7-11ea-8583-0d54e4646a2f.png)
