### ISSUE TITLE
[Jobs module]: Vancouver appears under Europe

### ISSUE THREAD

**Issue by rediris** [gymnasium/tracker#204]
<img width="319" alt="Screen Shot 2021-12-16 at 3 37 11 PM" src="https://user-images.githubusercontent.com/1010395/146445626-c30f3f3c-fc86-4b5e-b688-d8be375051c8.png">

It does also appear correctly under "Canada"

**Comment by andrewpmiller** [comment]
In fairness... they do have the Queen of England on their money... 👑
