### ISSUE TITLE
GYM-109 Lesson 6 missing content in assignments section

### ISSUE THREAD

**Issue by jgagne** [gymnasium/tracker#218]
## What

GYM-109 Lesson 6 Assignments:

> •

- Empty list item, no content, marker only
- Consider adding this content:
  - Quiz
  - No assignment. (If true?)

### Video

- No mention of quiz or assignment in Further Research (chapter) video content.
  - Note: Not an issue.

### PDF

- Page 3 — Assignments: https://gymnasium.github.io/GYM-109/Lesson_Files/RDF_Lesson_6_Handout.pdf
  - Included in: https://github.com/gymnasium/GYM-109/blob/master/Lesson_Files/RDF_All_Course_Assets.zip

**Comment by rediris** [comment]
TODO:
gather documents and edit!
