### ISSUE TITLE
Refactor collection page meta includes

### ISSUE THREAD

**Issue by andrewpmiller** [gymnasium/tracker#22]
Meta includes for collections pages should use a single layout and individual markdown files (DRY).

Consider generalizing the Take 5 meta layout to address this issue as well as for the meta headers when migrating webinars to gymcms (#21).

**Comment by mbifulco** [comment]
Is there a way to put all of the hub page files together in addition to this?

Something like: 
```
hub-pages
  prototyping
    bottom.html
    index.html 
    meta.html
    top.html
  ux-design
    bottom.html
    index.html
    meta.html
    top.html
```

**Comment by andrewpmiller** [comment]
Yes — the file structure in the repo can be (almost) anything. Your suggestion makes good sense. The meta layout file would still go in `_layouts`, but my plan is to define the meta content for each colllection page in the frontmatter of a markdown file — i.e.  `hub-pages/[collection]/meta.md`

Furthermore, we could also change `hub-pages` to `collections` for clarity... but that would require updates to the edx templates since it would make sense that the includes would be generated/served at `/static/collections/ux-design-top/` (for example) instead.
