### ISSUE TITLE
Update home page links

### ISSUE THREAD

**Issue by jgagne** [gymnasium/tracker#238]
Home page: thegymnasium.com

### Skip to main content

Line: 225

Accessibility issue, broken fragment: 
  - `<a class="nav-skip sr-only sr-only-focusable" href="#main">Skip to main content</a>`

### Permanent redirect update

Line: 732

Permanent redirect, link should be updated:
  - https://www.fastcompany.com/3024661/innovation-agents/hacking-hack-schools-to-make-them-work redirected to https://www.fastcompany.com/3024661/hacking-hack-schools-to-make-them-work

**Comment by rediris** [comment]
Add `id="main"` to an element on the home page
