### ISSUE TITLE
Implement automated visual testing

### ISSUE THREAD

**Issue by andrewpmiller** [gymnasium/tracker#257]
In our ongoing effort to improve operational efficiency and to deliver the best experience for our learners...
   
_and_ given the fact that seemingly simple changes can have cascading effects across the site...
   
_especially_ considering the tightly coupled nature of the edX theme, our customizations of that theme, and our use of the GymCMS to influence the display layer...
   
**There is a very obvious value to knowing when the site is not rendering as expected.**

We need to avoid issues like [this](https://github.com/gymnasium/tracker/issues/251)

**Comment by rediris** [comment]
Related rainy day card: https://github.com/orgs/gymnasium/projects/5#card-62430600

**Comment by rediris** [comment]
Some things to investigate:

**Cypress**
* https://github.com/marketplace/actions/cypress-io
* https://www.useanvil.com/blog/engineering/cypress-snapshot-testing/
* https://medium.com/@mohsanriaz224/visual-snapshot-testing-with-cypress-35c27a9316f4
* https://learn.cypress.io/testing-your-first-application/cypress-command-logs-snapshots-and-aliases
* https://www.freecodecamp.org/news/how-to-add-screenshot-testing-with-cypress-to-your-project/
* https://docs.cypress.io/api/commands/screenshot

**Comment by andrewpmiller** [comment]
> Related rainy day card: [github.com/orgs/gymnasium/projects/5#card-62430600](https://github.com/orgs/gymnasium/projects/5#card-62430600)

![](https://media.giphy.com/media/5W5TOAKuoZfa0/giphy.gif)

**Comment by rediris** [comment]
Other things to check:
- https://percy.io/

**Comment by rediris** [comment]
A working solution (although it could use more automation): https://github.com/gymnasium/gym-snaps
