### ISSUE TITLE
[Bug]: Footer links on login/register page are underlined

### ISSUE THREAD

**Issue by rediris** [gymnasium/tracker#279]
* text links & image links

<img width="1273" alt="Screen Shot 2022-09-08 at 11 28 54 AM" src="https://user-images.githubusercontent.com/1010395/189163247-79267edf-7192-46d9-81c6-c8c2153b2f34.png">

**Comment by rediris** [comment]
In doing some initial research, it appears the reason this is happening is because of how the page is built in the theme. My suggestion is to address it on the theme level instead of using CSS overrides to fix it.

**Comment by rediris** [comment]
I believe the culprit is an illegally closed `div` tag: https://github.com/gymnasium/openedx-theme/blob/hawthorn/staging/lms/templates/student_account/login_and_register.html#L44

**Comment by andrewpmiller** [comment]
![what?](https://media.giphy.com/media/8b9Xax6L7qtAkAimGm/giphy.gif)
