### ISSUE TITLE
Add webinar container pages to edX

### ISSUE THREAD

**Issue by andrewpmiller** [gymnasium/tracker#28]
## Container pages required for upcoming and past webinars:

Title | Path on CMS | Gym Staging | Gym Production
-- | -- | -- | --
Remote Work: Can it Work for You? | /static/webinars/remote-work | https://courses.gymna.si/webinars/remote-work | https://thegymnasium.com/webinars/remote-work
UX Design: Prototyping as Process | /static/webinars/prototyping-as-process | https://courses.gymna.si/webinars/prototyping-as-process | https://thegymnasium.com/webinars/prototyping-as-process
Planning Before Pixels: Create with Purpose | /static/webinars/planning-before-pixels | https://courses.gymna.si/webinars/planning-before-pixels | https://thegymnasium.com/webinars/planning-before-pixels
The Future of Web Layout | /static/webinars/future-of-web-layout | https://courses.gymna.si/webinars/future-of-web-layout | https://thegymnasium.com/webinars/future-of-web-layout
Rethinking Full Stack: Cost and Compromise | /static/webinars/rethinking-full-stack | https://courses.gymna.si/webinars/rethinking-full-stack | https://thegymnasium.com/webinars/rethinking-full-stack
Design Systems and Creativity: Unlikely Allies | /static/webinars/design-systems-and-creativity | https://courses.gymna.si/webinars/design-systems-and-creativity | https://thegymnasium.com/webinars/design-systems-and-creativity
Keeping Up with JavaScript is a Full-time Job | /static/webinars/keeping-up-with-javascript | https://courses.gymna.si/webinars/keeping-up-with-javascript | https://thegymnasium.com/webinars/keeping-up-with-javascript
The State of Responsive Design | /static/webinars/state-of-responsive-design | https://courses.gymna.si/webinars/state-of-responsive-design | https://thegymnasium.com/webinars/state-of-responsive-design
Web Design is Hard | /static/webinars/web-design-is-hard | https://courses.gymna.si/webinars/web-design-is-hard | https://thegymnasium.com/webinars/web-design-is-hard
Right-Sizing Your Rapid Prototypes for Web & Mobile | /static/webinars/right-sizing-your-rapid-prototypes | https://courses.gymna.si/webinars/right-sizing-your-rapid-prototypes | https://thegymnasium.com/webinars/right-sizing-your-rapid-prototypes
Designing for Real People: Making the Case for Meaningful UX | /static/webinars/designing-for-real-people | https://courses.gymna.si/webinars/designing-for-real-people | https://thegymnasium.com/webinars/designing-for-real-people
Designing for Understanding: Create Meaningful Interactions for Web and Mobile | /static/webinars/designing-for-understanding | https://courses.gymna.si/webinars/designing-for-understanding | https://thegymnasium.com/webinars/designing-for-understanding

**Comment by mbifulco** [comment]
On it! Thanks for the detailed issue, @andrewpmiller.  That table is perfect for this 😍

**Comment by mbifulco** [comment]
Hey @andrewpmiller will these also have accompanying `meta` includes for header/SEO content?

**Comment by mbifulco** [comment]
I've got a similar question for the hub page `thegymnasium.com/webinars` - do you want me to set that up like the ux landing page, etc, with top/jobs-module/bottom? Right now it's just a single-body import

**Comment by andrewpmiller** [comment]
Hey @mbifulco 
1. Metas: yes, there are meta includes for each webinar... the path to those is similar... 
`[staging/prod CMS]/static/webinars/meta/[webinar name]`

eg: https://deploy-preview-319--gymcms.netlify.com/static/webinars/meta/designing-for-understanding/

2. Webinars landing page: this container already exists... staging and production gym environments point to a placeholder page on the cms (`/static/webinars`) - it is a standard container, no need to split it for jobs. I think it can use the standard metas that other static pages use (no need for a custom meta for this one).

**Comment by andrewpmiller** [comment]
And... @mbifulco let me know if you’d like a generated list of paths for the meta includes... happy to do that if it simplifies your task at all.

**Comment by mbifulco** [comment]
No need - I'll get those up very shortly  🇲🇴

**Comment by mbifulco** [comment]
Meta bits are added https://github.com/gymnasium/edx-theme/pull/151/commits/4f0b67ce99f96b463003fd4595bd0d0dac57d420.

There wasn't really a general / static landing page include for meta stuff, so I added one at `static/hub-pages/meta/webinars/`.  If there's nothing on CMS, that'll just put a comment in the HTML header, so it's fine to leave it blank until we decide we need it. 

Waiting for config update on staging, then we'll be able to test with CMS 👍
