### ISSUE TITLE
Test favicon sizes and use

### ISSUE THREAD

**Issue by jgagne** [gymnasium/tracker#287]
- https://github.com/gymnasium/gymcms/pull/806#discussion_r977897746

## Things to do
- [ ] Add Gymnasium favicon to theme root
- [ ] investigate claim of ill formed favicon: https://realfavicongenerator.net/favicon_checker?protocol=https&site=thegymnasium.com%2F

## Tools
- http://www.colinkeany.com/favicon-checker/

**Comment by rediris** [comment]
Solution: serve up favicon from site root (in addition to what we already do)
