### ISSUE TITLE
[Bug]: email password reset landing page missing CSS/meta

### ISSUE THREAD

**Issue by rediris** [gymnasium/tracker#289]
This screenshot was provided by a student having trouble resetting their password.

When a student clicks on the password reset link in their email, the resultant page is less than desirable.

<img width="687" alt="Screen Shot 2022-10-10 at 1 28 02 PM" src="https://user-images.githubusercontent.com/1010395/194922373-27ed5343-64c1-40cb-8071-89d53f6c020f.png">

**Comment by andrewpmiller** [comment]
- [ ] Add to the inventory of auto-screenshots 😉

**Comment by rediris** [comment]
> * [ ]  Add to the inventory of auto-screenshots 😉

Totally, but first we'll need to attach a string of characters to the url to ensure the page actually shows uP!

**Comment by rediris** [comment]
> > * [ ]   Add to the inventory of auto-screenshots 😉
> 
> Totally, but first we'll need to attach a string of characters to the url to ensure the page actually shows uP!

Oh wait, it's as easy as this: https://thegymnasium.com/password_reset_confirm/this-is-a-test-only/

**Comment by rediris** [comment]
Fixed: https://thegymnasium.com/password_reset_confirm/this-is-a-test-only/
