### ISSUE TITLE
Incorrect catalog content for GYM-014

### ISSUE THREAD

**Issue by andrewpmiller** [gymnasium/tracker#3]
"This course is for" bullet points on the course [about](https://thegymnasium.com/courses/course-v1:GYM+014+0/about) page are incorrect. They should match the items on the catalog page.

**Correct copy:**

- Anyone interested in building design systems
- Anyone interested in building website or web app prototypes
- UX designers with coding chops

Studio: Settings > Schedule & Details > Course Overview

**Comment by jeremyosborn** [comment]
This has been fixed on https://studio.gymna.si/settings/details/course-v1:GYM+014+staging
