### ISSUE TITLE
Multiple typos in Dataviz course outline and syllabus

### ISSUE THREAD

**Issue by andrewpmiller** [gymnasium/tracker#30]
https://thegymnasium.com/courses/course-v1:GYM+013+0/about
https://thegymnasium.com/courses/course-v1:GYM+013+0/info

Typos in bold:

Chapter 2: Interface Overview 

Begin working right away with Maya by exploring the interface. You'll learn the role of modes within Maya and what effect they have on **yoru** project. You'll also add a simple 3D shape and discover **how how** to select objects and components **withn** a scene, and finally, you'll explore a number of other aspects of the interface that may come in handy later.

**Comment by jeremyosborn** [comment]
Fixed on the following pages:
1. https://studio.gymna.si/settings/details/course-v1:GYM+013+staging
2. https://studio.gymna.si/course_info/course-v1:GYM+013+staging
