### ISSUE TITLE
Jobs feed is broken

### ISSUE THREAD

**Issue by andrewpmiller** [gymnasium/tracker#301]
**Home:**
<img width="793" alt="image" src="https://user-images.githubusercontent.com/5747506/200693033-f9376efe-dafe-4db2-99a0-a62522dc0277.png">

**Jobs:**
<img width="830" alt="image" src="https://user-images.githubusercontent.com/5747506/200693209-b7199fa4-27c4-4d37-8a60-de9132244c1b.png">

👉 Same result when selecting another option from the dropdown

- Is there a way we can automatically test this to know when it fails?
- Is there a better error handling strategy?

**Comment by rediris** [comment]
It looks like there's another illegal character that's breaking the feed.

https://assets.aquent.com/apps/gym/jobs.json?limit=1500

When running it through a JSON validator:

```
Parse error on line 6401:
...84771",
"city" : "東京都渋谷区（最寄り駅：東京メトロ銀座
----------------------^
Expecting 'STRING', 'NUMBER', 'NULL', 'TRUE', 'FALSE', '{', '[', got 'undefined'
```

**Comment by rediris** [comment]
Fixed (for now)...
