### ISSUE TITLE
Update Take 5 URL

### ISSUE THREAD

**Issue by jgagne** [gymnasium/tracker#303]
## Update Take 5 URL

`make` to `making` – confirm with @jeremyosborn 

- Before: https://thegymnasium.com/courses/take5/make-a-great-first-impression-with-your-portfolio
- After: https://thegymnasium.com/courses/take5/making-a-great-first-impression-with-your-portfolio

## Notes
We will also need to set up a redirect from the old URL to the new.

**Comment by rediris** [comment]
Hi @jeremyosborn, confirming this is indeed what we want to do?
