### ISSUE TITLE
Horizontal scroll - space on courseware pages

### ISSUE THREAD

**Issue by andrewpmiller** [gymnasium/tracker#333]
Courseware pages (i.e. "Lessons") have additional margin space (and the horizontal scrollbar appears).

<img width="1504" alt="image" src="https://user-images.githubusercontent.com/5747506/236220068-062f38f8-906c-4f8b-af5a-e7388ba229b3.png">

**Comment by rediris** [comment]
I found the issue - it’s only visible for staff and it’s entirely the blue staff action bar at the top. Happens on /info and /courseware pages. Specifically, it's the hidden button inside the div, which needs to have a `width: auto` set to remedy the issue.
