### ISSUE TITLE
Remote jobs displays as default select option in Find Work module

### ISSUE THREAD

**Issue by jgagne** [gymnasium/tracker#39]
**Describe the bug**
Remote jobs displays as default select option in Find Work module on the home page and courses page, outside of the work in progress Remote Work page.

**URL where bug occurs (if applicable)**

- https://thegymnasium.com
- https://thegymnasium.com/courses

**Expected behavior**
Default select option set by location, but not by Remote jobs yet?

**Screenshots**

![gym-home-page-remote-find-work-module](https://user-images.githubusercontent.com/5142085/77956108-58004280-729f-11ea-9e8a-f0c5d83a5074.png)
![gym-courses-page-remote-find-work-module](https://user-images.githubusercontent.com/5142085/77956138-62224100-729f-11ea-8e8b-367a8c52d910.png)
![gym-courses-page-detail-remote-find-work-module](https://user-images.githubusercontent.com/5142085/77956128-5f275080-729f-11ea-9d76-5e48ec25b41f.png)

**Comment by mbifulco** [comment]
Geo is defaulted to remote _everywhere_ for now - once the "economy" is "working" again, we will switch this back to your-nearest-geo
