### ISSUE TITLE
Incorrect Find Work header text color

### ISSUE THREAD

**Issue by jgagne** [gymnasium/tracker#40]
**Describe the bug**
Current Find Work header text color appears grayed out, above and below the "Remote jobs" select option — possibly a regression issue.

**URL where bug occurs (if applicable)**
- https://thegymnasium.com/courses

**Expected behavior**
Find Work header text color should have a higher contrast ratio to match text color found in "Full Courses" heading and adjacent body text (`#222`?).

**Screenshots**

![gym-courses-page-find-work-module-type-detail](https://user-images.githubusercontent.com/5142085/77957966-52f0c280-72a2-11ea-8f44-3c78bf9b7162.png)

**Comment by mbifulco** [comment]
El Capitan @andrewpmiller's brilliant suggestion to fix - let's make the Find Work module _always_ have a dark background:

![image](https://user-images.githubusercontent.com/1844496/80224800-35501800-8618-11ea-8a44-80bb42701304.png)
(obviously this needs some @jgagne magic)

**Comment by jgagne** [comment]
## Notes

**Current font-smoothing rule:**

```
/** current font-smoothing enabled */
body {
  -webkit-font-smoothing: antialiased;
  -moz-osx-font-smoothing: grayscale;
}
```

**Screenshot of current font-smoothing rule:**

![forum-font-smoothing-enabled](https://user-images.githubusercontent.com/5142085/80522292-54251600-895a-11ea-8312-62297c326bbb.png)


**Possible solutions:**

```
/** auto font-smoothing: let the browser decide */
body {
  -webkit-font-smoothing: auto;
  -moz-osx-font-smoothing: auto;
}
```

or

```
/** auto font-smoothing for knockout text in navigation: let the browser decide */
#primary-nav,
#secondary-nav,
#contentinfo {
  -webkit-font-smoothing: auto;
  -moz-osx-font-smoothing: auto;
}
```

**Comment by jgagne** [comment]
@mbifulco — A possible solution for the issue:

**CSS**

```css
.sidebar #jobs-microservice-frame {
  min-width: 116% !important;
  background-color: #444;
  padding: 1.4em;
  margin-top: -1.4em;
  margin-left: -1.4em;
}
```

**Before**

![gym-sidebar-find-work-before](https://user-images.githubusercontent.com/5142085/80735124-397baa00-8ade-11ea-8284-1bce918aaa08.png)

**After**

![gym-sidebar-find-work-after](https://user-images.githubusercontent.com/5142085/80735147-426c7b80-8ade-11ea-8a66-a167b5fa8414.png)

**Comment by mbifulco** [comment]
Drop changes in a style tag here https://github.com/gymnasium/gymcms/blob/staging/system-status.html
