### ISSUE TITLE
Dashboard should display the highest final course grade earned

### ISSUE THREAD

**Issue by mbifulco** [gymnasium/tracker#44]
**Describe the bug**
A couple students have reported their dashboard showing what appears to be the _first grade_ they submitted on the final exam for a given course.  This is misleading if they get a higher grade on a retry of the exam.  We'd like to show the highest grade they achieve, regardless of whether it is their first or second attempt.

**URL where bug occurs (if applicable)**
https://thegymnasium.com/dashboard

**To Reproduce**
1. take a final exam for any course, get 100
1. take it again, and get some questions wrong
1. you'll see your later grade, but we should display 💯

TODO: 
* Look into updating dashboard & editing logic for accredible call 
* Needs additional analysis

**Comment by mbifulco** [comment]
This needs to be tested on hawthorn

**Comment by mbifulco** [comment]
Explore this for:
- fully self-paced courses (as hawthorn/edx does it)
- traditional gymnasium self-paced courses

**Comment by rediris** [comment]
Notes:

* Update credential API: https://accrediblecredentialapi.docs.apiary.io/#reference/credentials/credential/update-a-credential
* Will need to update this chunk with some revised logic: https://github.com/gymnasium/openedx-theme/blob/ea2d6e200c724f59ce880ef6ab9351f484214071/lms/templates/problem.html#L143-L284

**Comment by rediris** [comment]
The resolution of this is getting shifted to the Accredible team, as it requires updates to the plugin. See: https://trello.com/b/jXPeY8te/aquent-appsembler-shared-board

**Comment by rediris** [comment]
Resolved via: https://github.com/appsembler/accredible/pull/5
