### ISSUE TITLE
Homework and Materials links in courseware need styling

### ISSUE THREAD

**Issue by andrewpmiller** [gymnasium/tracker#54]
### Screenshot

![image-2017-12-15-12-25-29-569](https://user-images.githubusercontent.com/5747506/79796788-23265f00-8324-11ea-9a90-06a71288c3d8.png)

### URL

https://thegymnasium.com/courses/GYM/107/0/courseware/0d19a11344524234a52434b56dc8cdbb/265a21a3d26045709225df61b4717368/

**Comment by jgagne** [comment]
## Style Update

**Notes**

- Avoiding orange on a white background for links, but keeping the underline for interaction states
- HTML/CSS updates via Studio per instance
  -  Thoughts on having a general edx related stylesheet include for such updates, that could then be updated via GYMCMS and wouldn't need to reference per XBlock or other component?

![gym-handout-style](https://user-images.githubusercontent.com/5142085/81084777-55a78e80-8ec4-11ea-9790-5fcd8dd0c7c3.png)

**Interaction State**

![gym-handout-style-hover](https://user-images.githubusercontent.com/5142085/81084829-6821c800-8ec4-11ea-9d75-5717da98faff.png)

**Comment by andrewpmiller** [comment]
@jgagne — I'm not sure about the default state with the partial underline. While I'm a fan of _a_ hover state (in the abstract), I think we need to commit one way or the other with the underlined link text. Accessibility guidelines would suggest we display the underline always... not just on hover. The ⬇️ PDF part makes the decision a bit complicated. I'd sooner remove the arrow and put the pdf in parentheses (and all linked/underlined). 
If GitHub didn't hide the underline... and I could make the text all black... something like this:

[Handout (PDF)](#)

**Comment by jgagne** [comment]
## Take 2

Based on suggested simplification ↑ of content and style.

**Notes**

- Linked text underlined by default
- Hover/Focus state defined by a bolder/thicker underline

**Default State**

![gym-handout-style](https://user-images.githubusercontent.com/5142085/81187904-ab427080-8f82-11ea-8633-6d4bd3fe339f.png)

**Interaction State**

![gym-handout-style-hover-focus](https://user-images.githubusercontent.com/5142085/81187961-bc8b7d00-8f82-11ea-8d04-3020c86500a0.png)

**Comment by andrewpmiller** [comment]
@jgagne this is great! If you feel like the text link needs some visual distinction or adornment, the ⬇️ _could_ still appear with the text — either before "Handout" or between "Handout" and "(PDF)" but I'm not sure it's necessary. Something to test with users?

**Comment by jgagne** [comment]
The inclusion of (PDF), (ZIP), etc. feels like a good balance of visual distinction and accessibility enhancement. Updated link styles would definitely be something to test with users.

**Comment by mbifulco** [comment]
Let's go forward with this as it is now @jgagne - let me know if you want help getting these added to existing courses
