### ISSUE TITLE
Ragged left edge is killing me slowly

### ISSUE THREAD

**Issue by andrewpmiller** [gymnasium/tracker#55]
![image-2017-12-15-11-38-52-319](https://user-images.githubusercontent.com/5747506/79797019-8adcaa00-8324-11ea-9a07-f419720c9224.png)

**Comment by mbifulco** [comment]
Add a `logo.html` to the CMS which renders _just_ this snippet from the site's current footer:

```html
<img class="gymnasium-logo" alt="Aquent Gymnasium" src="https://staging.thegymcms.com/img/brand/png/gymnasium-logo-white-4x.png" srcset="https://staging.thegymcms.com/img/brand/svg/gymnasium-logo-white.svg" width="200" height="23" decoding="async">
```

**Comment by mbifulco** [comment]
Should have sent a poet 😭 

![image](https://user-images.githubusercontent.com/1844496/98869977-8f8fb980-2440-11eb-86a2-8401bc5ae682.png)
