### ISSUE TITLE
UI: Login page - "New To Gymnasium" should be Brandon font

### ISSUE THREAD

**Issue by andrewpmiller** [gymnasium/tracker#56]
![image-2017-12-15-11-19-22-335](https://user-images.githubusercontent.com/5747506/79797091-a647b500-8324-11ea-868b-801b687dd3ac.png)

This should be in Brandon like the "Sign in" title on the page.

@jgagne - should "New to Gymnasium" and "Sign In" both be centered, or left aligned, or staggered?

**Comment by mbifulco** [comment]
This has to do with `font-family: "Brandon Grotesque";` in css/sass - it should be `font-family: brandon-grotesque`

**Comment by rediris** [comment]
See https://github.com/gymnasium/gymcms/pull/679
