### ISSUE TITLE
If we re-enable LinkedIn: Spacing around LinkedIn button needs adjusting

### ISSUE THREAD

**Issue by andrewpmiller** [gymnasium/tracker#57]
The spacing between the header ("Create an account using") and the top of the LinkedIn button on the registration screen is incorrect. 

@jgagne — please recommend the appropriate padding (see screenshot).

https://thegymnasium.com/register

![register-spacing](https://user-images.githubusercontent.com/5747506/79797845-fffcaf00-8325-11ea-8fef-e997621eb2e1.png)

**Note from the original Jira Ticket:**

@jgagne commented:

> **Screenshot Comparison**
> 
> See `sign-in-create-account-comparison.png` for reference.
> 
> **HTML/CSS Comp**
> 
> Click "Create an account" button at the bottom to view spacing in question:
> 
> https://jgagne.github.io/gym-enhancements/login-linkedin/

![sign-in-create-account-comparison](https://user-images.githubusercontent.com/5747506/79798174-98932f00-8326-11ea-8488-bb9c63bea5a6.png)

**Comment by jgagne** [comment]
## Notes

Update heading `font-family` value; from "Brandon Grotesque" to "brandon-grotesque":

**Before:**

```
font-family: "Brandon Grotesque", "Helvetica Neue", Helvetica, sans-serif;
padding: 0.75em 0;
```

**After:**

```
font-family: "brandon-grotesque", "Helvetica Neue", Helvetica, sans-serif;
padding: 0.5em 0 0.75em;
```

(Optionally update `padding` value, to decrease `padding-top` value, for better spacing in this particular context, if nondestructive elsewhere.)

See https://github.com/gymnasium/edx-theme/blob/c87cf6d556e880b6bfdddf7528d167d9e20ccc11/lms/static/sass/_register.scss#L82-L83

Also update additional instance of `font-family` value "Brandon Grotesque" to "brandon-grotesque" (if applicable):

- https://github.com/gymnasium/edx-theme/blob/c87cf6d556e880b6bfdddf7528d167d9e20ccc11/lms/static/sass/_register.scss#L52

**Comment by mbifulco** [comment]
This is related to #56
