### ISSUE TITLE
Forum - Global primary and footer navigation not correctly styled

### ISSUE THREAD

**Issue by andrewpmiller** [gymnasium/tracker#59]
When viewing the course forum, global text navigation styles in the primary and footer navigation and text are not correct.

**Site-wide:** 

![image](https://user-images.githubusercontent.com/5747506/79797531-68975c00-8325-11ea-9bca-3b13453257a3.png)

https://thegymnasium.com/courses/GYM/107/0/info

**Forum:**

![image](https://user-images.githubusercontent.com/5747506/79797616-92e91980-8325-11ea-876b-0e7356598e6e.png)

https://thegymnasium.com/courses/GYM/107/0/discussion/forum

Primary nav on the forum has the wrong weight.
<img width="1167" alt="Screen Shot 2021-11-24 at 1 16 27 PM" src="https://user-images.githubusercontent.com/1010395/143294016-a0e7e4cb-5423-41e2-9fc9-ccaf0772a1fe.png">

**Comment by andrewpmiller** [comment]
Type weight appearance is still inconsistent between the forum and elsewhere on the site.

![image](https://user-images.githubusercontent.com/5747506/80414046-68a3d880-889e-11ea-8a35-13b011ee62f1.png)


### Homepage

https://courses.gymna.si/

![image](https://user-images.githubusercontent.com/5747506/80413352-5b3a1e80-889d-11ea-9ead-bac8c9776105.png)

### Forum

https://courses.gymna.si/courses/course-v1:GYM+109+staging/discussion/forum

![image](https://user-images.githubusercontent.com/5747506/80413442-79a01a00-889d-11ea-8d13-646f5df5a2e3.png)

**Comment by jgagne** [comment]
Working with @mbifulco to resolve font-smoothing issues. All other footer layout related issues resolved.

**Comment by jgagne** [comment]
## Notes

**Current font-smoothing rule:**

```
/** current font-smoothing enabled */
body {
  -webkit-font-smoothing: antialiased;
  -moz-osx-font-smoothing: grayscale;
}
```

**Screenshot of current font-smoothing rule:**

![forum-font-smoothing-enabled](https://user-images.githubusercontent.com/5142085/80522292-54251600-895a-11ea-8312-62297c326bbb.png)


**Possible solutions:**

```
/** auto font-smoothing: let the browser decide */
body {
  -webkit-font-smoothing: auto;
  -moz-osx-font-smoothing: auto;
}
```

or

```
/** auto font-smoothing for knockout text in navigation: let the browser decide */
#primary-nav,
#secondary-nav,
#contentinfo {
  -webkit-font-smoothing: auto;
  -moz-osx-font-smoothing: auto;
}
```

**Comment by mbifulco** [comment]
@mbifulco to test both solutions above, and deploy via CMS
