### ISSUE TITLE
Forum Post Text, font-family change

### ISSUE THREAD

**Issue by jgagne** [gymnasium/tracker#62]
**Description**
Forum: Post text (comments/responses) should be rendered as a "Helvetica" variant instead of "Brandon Grotesque" for better readability.

**URL where bug occurs**
Forum posts/comments, see Jira screenshot below if available.

**Screenshots**
[form-post-text.png](https://jira.aquent.io/secure/attachment/19766/form-post-text.png)

**Comment by mbifulco** [comment]
Address at the same time as #43  #45  #59  ideally

**Comment by jgagne** [comment]
This issue looks resolved:

![forum-posts-comments-font](https://user-images.githubusercontent.com/5142085/80245779-52491300-8639-11ea-9577-ccf1b7cb4424.png)

@mbifulco please confirm, and check against initial screenshot in Jira [form-post-text.png](https://jira.aquent.io/secure/attachment/19766/form-post-text.png) (as I am inactive to log in).
