### ISSUE TITLE
Final Exam instruction text font-sizing and style

### ISSUE THREAD

**Issue by jgagne** [gymnasium/tracker#63]
**Description**
- Final Exam instruction text font-sizing seems small "You’re ready for your final exam!, Remember, Instructions, and Good luck."
- "Remember" and "Instructions" should be uppercase.

**URL where bug occurs**
Final Exam Instructions for full courses: 

![final-exam-instructions](https://user-images.githubusercontent.com/5142085/80243301-fb413f00-8634-11ea-8c86-e1876818eecf.png)
**Screenshots**
Comp reference:
![final-exam-instructions-comp](https://user-images.githubusercontent.com/5142085/80243183-bae1c100-8634-11ea-8b04-5b3f8040878d.png)

**Comment by mbifulco** [comment]
`Final Exam` needs its `font-weight` set, and font-sizes on the blurb may need to be adjusted

**Comment by jgagne** [comment]
Consider closing…

![gym-final-exam-instructions-style](https://user-images.githubusercontent.com/5142085/137533191-5c134a5a-7364-4940-85bd-9d60e57c0c84.png)
