### ISSUE TITLE
TEST YOUR KNOWLEDGE: If I get every answer wrong score is not displayed

### ISSUE THREAD

**Issue by jgagne** [gymnasium/tracker#65]
**Description**

Course: RWD and JSF 
Test Your knowledge Quiz

I got every answer wrong, and my score never displayed. 
I have used up all of my submissions (1 of 1) so it should show my score. Score says (100 Points Possible)

**URL where bug occurs**
http://courses.gymna.si/courses/Gymnasium/101/0/courseware/eceb571b0bec420a93ca18c7fba8ee55/a48294d1dc894c6989494e16794e96d5/

**Screenshots**
[Screen Shot 2015-10-16 at 4.35.19 PM.png](https://jira.aquent.io/secure/attachment/19554/Screen+Shot+2015-10-16+at+4.35.19+PM.png)

**Comment by mbifulco** [comment]
Mike to check this on new platform

**Comment by mbifulco** [comment]
Fixed on Hawthorn!
