### ISSUE TITLE
Update jobs container page template

### ISSUE THREAD

**Issue by jgagne** [gymnasium/tracker#70]
**Description:**

Update jobs container page template to include updated jobs page-related includes, same as the set up for the Remote Work page container (`/remote-work`), rather than the current `jobs.md`.

See `top.html` and `bottom.html` includes: https://github.com/gymnasium/gymcms/tree/staging/jobs

**Meta permalink:**
- `/static/jobs/meta/jobs-meta/`

**Preview:**
- Deploy Preview: https://deploy-preview-395--thegymcms.netlify.app/tests/jobs/
- Screenshot (without job module include): https://user-images.githubusercontent.com/5142085/80243465-44918e80-8635-11ea-9d2b-79a11d7fce9f.png

**Reference:**
- https://github.com/gymnasium/gymcms/pull/39

**Comment by mbifulco** [comment]
@jgagne I'll have this in a branch for you to review tonight or tomorrow
