### ISSUE TITLE
Locate SVG files for VT and Aquent logo

### ISSUE THREAD

**Issue by mbifulco** [gymnasium/tracker#72]
I just converted all of the images on the new site's footer to svg.  I'd love to do the same for the VT/Aquent logos in the header, too.

**Comment by jgagne** [comment]
@mbifulco I'll update https://github.com/gymnasium/gymcms/tree/staging/img/gym-aq-vt-logos/svg to include an Aquent "A". (And for the grayed-out version; maybe could use CSS to do that `filter: grayscale(100%);`.)

**Comment by jgagne** [comment]
See also https://github.com/gymnasium/gymcms/tree/staging/img/social/icons/svg

**Comment by mbifulco** [comment]
Super helpful, thank you! That's everything I need.  The greyscale filter should do the trick.
