### ISSUE TITLE
Catalog content for GYM-004 (WordPress) is not correct

### ISSUE THREAD

**Issue by andrewpmiller** [gymnasium/tracker#74]
The intro copy for **Creating a WordPress Theme** refers to the course title incorrectly. It should not be _Creating a WordPress Theme from Scratch_.

![image](https://user-images.githubusercontent.com/5747506/83907691-d6f87800-a733-11ea-9b03-e9379ea91eb6.png)

Staging: https://courses.gymna.si/courses/GYM/004/staging/about
Production: https://thegymnasium.com/courses/GYM/004/0/about

**This must be fixed in Studio**

Settings > Schedule & Details > Course Overview

**Staging:** https://studio.gymna.si/settings/details/GYM/004/staging
**Production:** https://studio.thegymnasium.com/settings/details/GYM/004/0

**Comment by jgagne** [comment]
"From Scratch" is removed.

Staging: https://courses.gymna.si/courses/GYM/004/staging/about
Production: https://thegymnasium.com/courses/GYM/004/0/about
