### ISSUE TITLE
Catalog content for GYM-006 (GitHub) has a typo

### ISSUE THREAD

**Issue by andrewpmiller** [gymnasium/tracker#75]
The intro copy for **Introduction to Git and GitHub** has incorrect capitalization for "Github" — should be an upper case H.

![image](https://user-images.githubusercontent.com/5747506/83908467-2d19eb00-a735-11ea-9050-5845fdf42f5a.png)

Staging: https://courses.gymna.si/courses/GYM/006/staging/about
Production: https://thegymnasium.com/courses/GYM/006/0/about

**This must be fixed in Studio**

Settings > Schedule & Details > Course Overview

**Staging:** https://studio.gymna.si/settings/details/GYM/006/staging
**Production:** https://studio.thegymnasium.com/settings/details/GYM/006/0

**Comment by jgagne** [comment]
Capitalization of GitHub, throughout the page, is up-to-date.

**Comment by jgagne** [comment]
Github is now GitHub.

Staging: https://courses.gymna.si/courses/GYM/006/staging/about
Production: https://thegymnasium.com/courses/GYM/006/0/about
