### ISSUE TITLE
Cookie notification doesn't display the close "X" correctly

### ISSUE THREAD

**Issue by andrewpmiller** [gymnasium/tracker#77]
No visible way to close this:

![image](https://user-images.githubusercontent.com/5747506/86965429-86f74180-c135-11ea-84fd-504f1940dc1e.png)

We should see the "X" in the far right:

![image](https://user-images.githubusercontent.com/5747506/86965633-d8073580-c135-11ea-9d68-708cc5eacc5e.png)

**Comment by mbifulco** [comment]
Blah, how frustrating! Good catch @andrewpmiller

**Comment by andrewpmiller** [comment]
Reopened
