### ISSUE TITLE
Accessible link text color (no more orange on white)

### ISSUE THREAD

**Issue by andrewpmiller** [gymnasium/tracker#78]
The text link to the dashboard is orange. Also, should the overall type size(s) be increased?

**Files:** final-exam-modal.html and final-exam-modal-top.html

![image](https://user-images.githubusercontent.com/5747506/87166250-47496a80-c299-11ea-960c-51bec8968fd2.png)

**Comment by mbifulco** [comment]
Related to #63

**Comment by mbifulco** [comment]
To Do:

- [x] final exam `dashboard` link
- [ ] tertiary navigation text for courses ("lessons syllabus forum" on top of the page)

**Comment by mbifulco** [comment]
All done! 
![image](https://user-images.githubusercontent.com/1844496/98870656-979c2900-2441-11eb-8ade-825c45dc3ed7.png)
