### ISSUE TITLE
Course materials links are incorrect

### ISSUE THREAD

**Issue by andrewpmiller** [gymnasium/tracker#79]
### GYM-102 jQuery Building Blocks

- [ ] https://thegymnasium.com/courses/GYM/102/0/info
- [ ] https://courses.gymna.si/courses/GYM/102/staging/info

### GYM-001 Defeating Busy

 - [ ] Staging: https://courses.gymna.si/courses/GYM/001/staging/info
 - [ ] Production: https://thegymnasium.com/courses/GYM/001/0/info

### GYM-003 Grid Layout in Bootstrap

 - [ ] Staging: https://courses.gymna.si/courses/GYM/003/staging/info
 - [ ] Production: https://thegymnasium.com/courses/GYM/003/0/info

### GYM-004 Creating a Word Press Theme

  - [ ] Staging: https://courses.gymna.si/courses/GYM/004/staging/info
  - [ ] Production: https://thegymnasium.com/courses/GYM/004/0/info

**Comment by mbifulco** [comment]
Still need to determine whether production or staging is correct here - investigation needed
