### ISSUE TITLE
Make "Featured Courses" content available to AQ/VT

### ISSUE THREAD

**Issue by andrewpmiller** [gymnasium/tracker#80]
## Requirements

- A way to include 3 featured courses on AQ/VT
- Content updates automatically when it changes on the Gymnasium
- JSON is preferable

### End Result

![image](https://user-images.githubusercontent.com/5747506/88843972-f221ba00-d1af-11ea-8ff6-6ea8161238d3.png)

## Notes

- **Each course requires**:
  - image
  - background color
  - course title
  - course URL
  - course short description
  - course instructor
  - instructor detail

## Open Questions

- Are these short descriptions different from those in the meta includes?
- Do we rebuild the featured courses module at the same time?
- How will this work with `v. next`?

**Comment by jgagne** [comment]
> Are these short descriptions different from those in the meta includes?

Yes, typically they are a shorter short description. (We could eliminate the siloed Featured Courses variation and consolidate to a single short description that better fulfills the requirements.)

> Do we rebuild the featured courses module at the same time?

Yes. (Short answer.)

**Comment by jgagne** [comment]
Existing (partial) course JSON in our collection/hub-pages:
https://github.com/gymnasium/gymcms/blob/1fa0b7cba65fff637196bfc820e39904fa4da3fc/hub-pages/ux-design/bottom.html#L10-L108
