### ISSUE TITLE
Accessibility Collection container page needed

### ISSUE THREAD

**Issue by andrewpmiller** [gymnasium/tracker#83]
A container page is needed for the accessibility landing page (https://thegymnasium.com/accessibility)

**Note:** The initial release should not display a jobs module (will be needed for subsequent release)

Meta: `/static/hub-pages/meta/accessibility-collection-meta/`
Top: `/static/accessibility-top/`
Bottom: `/static/accessibility-bottom/`

See: gymnasium/gymcms#470

**Comment by jgagne** [comment]
@mbifulco Cool to close?

**Comment by mbifulco** [comment]
Closing!
