### ISSUE TITLE
[Hawthorn] Most landing pages are failing when they load

### ISSUE THREAD

**Issue by andrewpmiller** [gymnasium/tracker#94]
Click on a link to a landing page: https://courses.gymnasium.dev/ux-design
Page loads... until the **job module**... then redirects to a bad url

Note: This does not happen with https://courses.gymnasium.dev/accessibility — (which is not displaying a job module)

**Comment by mbifulco** [comment]
This was fixed by https://github.com/gymnasium/openedx-theme/pull/11 🎉
