### ISSUE TITLE
[Hawthorn] Webinars catalog links to webinar landing pages on previous staging environment

### ISSUE THREAD

**Issue by jgagne** [gymnasium/tracker#98]
**Description**

All "Watch Recording" links on the Webinars catalog landing page point to individual webinar landing pages on the previous staging environment instead of on the Hawthorn staging environment. 

For example: https://courses.gymna.si/webinars/decade-of-responsive-web-design instead of https://courses.gymnasium.dev/webinars/decade-of-responsive-web-design

Note: Potential GYMCMS configuration issue.

**URL where bug occurs**

 https://courses.gymnasium.dev/webinars

**Screenshots**

![webinars-individual-landing-page-urls](https://user-images.githubusercontent.com/5142085/98280766-df1a4500-1f69-11eb-805d-a09a12e98b8d.png)

**Comment by jgagne** [comment]
Note: Similar behavior from the Take 5 catalog: https://courses.gymnasium.dev/take5

**Comment by andrewpmiller** [comment]
@jgagne your suspicion is correct. The index pages for webinars and Take 5s (and possibly the landing pages) use conditional logic to construct the absolute paths of the links... eg: [Webinars links](https://github.com/gymnasium/gymcms/blob/894ef53053a4dd2b194a921bdedc3ba59f150152/webinars/webinars.html#L47-L68). This environment (.dev) is configured to pull CMS content for staging... and our staging content on the CMS assumes the URL to be courses.gymna.si.

**Comment by mbifulco** [comment]
Going to close this one out - this will be a non-bug once we move our Hawthorn staging server's DNS to point to courses.gymna.si... or however you say that.  Thanks for logging this @jgagne, and confirmation @andrewpmiller!
